
name: Deploy Reservation System Embed

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Create embed files
      run: |
        # Create embed directory
        mkdir -p embed-dist
        
        # Copy built assets
        cp -r dist/* embed-dist/
        
        # Create the embed HTML file
        cat > embed-dist/reservation-embed.html << 'EOF'
        <!DOCTYPE html>
        <html lang="hu">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Reservation System</title>
          <style>
            body {
              margin: 0;
              padding: 0;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
              background: transparent;
            }
            #root {
              width: 100%;
              min-height: 600px;
            }
            /* Iframe-specific styles */
            .reservation-embed {
              width: 100%;
              max-width: none;
              margin: 0;
              padding: 20px;
              box-sizing: border-box;
            }
          </style>
        </head>
        <body>
          <div id="root"></div>
          <script type="module" crossorigin src="./assets/reservation-system.js"></script>
          <link rel="stylesheet" href="./assets/reservation-system.css">
        </body>
        </html>
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./embed-dist
        publish_branch: gh-pages
