
# Deploy Reservation System to GitHub Pages
name: Deploy Reservation System to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build embed version
        run: npm run build:embed
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Create embed files
        run: |
          # Create embed directory
          mkdir -p embed-dist
          
          # Copy built assets
          cp -r dist-embed/* embed-dist/
          
          # Find the actual generated filenames
          JS_FILE=$(find embed-dist/assets -name "*.js" -type f | head -1 | sed 's|embed-dist/||')
          CSS_FILE=$(find embed-dist/assets -name "*.css" -type f | head -1 | sed 's|embed-dist/||')
          
          echo "Found JS file: $JS_FILE"
          echo "Found CSS file: $CSS_FILE"
          
          # Create the embed HTML file with dynamic asset references
          cat > embed-dist/reservation-embed.html << EOF
          <!DOCTYPE html>
          <html lang="hu">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Foglalási Rendszer</title>
            <style>
              body {
                margin: 0;
                padding: 0;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                background: transparent;
              }
              #root {
                width: 100%;
                min-height: 600px;
              }
              /* Iframe-specific styles */
              .reservation-embed {
                width: 100%;
                max-width: none;
                margin: 0;
                padding: 20px;
                box-sizing: border-box;
              }
            </style>
            <link rel="stylesheet" href="./$CSS_FILE">
          </head>
          <body>
            <div id="root"></div>
            <script type="module" crossorigin src="./$JS_FILE"></script>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './embed-dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
